services:
  postgres:
    image: postgres:17.4
    container_name: happy_cafe_admin_postgres_db_container
    environment:

      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - happy_cafe_admin_pgdata:/var/lib/postgresql/data

volumes:
  happy_cafe_admin_pgdata:
    driver: local