name: Happy Cafe Admin Backend CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: happy_cafe_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.201'

    - name: Create .env file
      run: |
        mkdir -p setup_dev
        cat > setup_dev/.env << EOL
        DB_HOST=localhost
        DB_PORT=5432
        DB_USER=username
        DB_PASSWORD=password
        ASPNETCORE_ENVIRONMENT=Development
        EOL

    - name: Restore dependencies
      run: dotnet restore HappyCafeAdmin.sln

    - name: Build
      run: dotnet build HappyCafeAdmin.sln --no-restore

    - name: Test
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: username
        DB_PASSWORD: password
        ASPNETCORE_ENVIRONMENT: Development
      run: dotnet test backend/Tests/Tests.csproj --no-build --verbosity normal 
